### PR TITLE
Correctly implement Tail in helpers

### PR DESCRIPTION
**Pull request by baconpaul**
1. Have the tail extension call tailGet not latencyGet
2. Add a correct (no plugin *) signature for tailGet
3. Remain the old (plugin *) signature for subclassers but mark
   it as deprecated

### CODE REVIEW

**Comment by abique** [comment]
Hi @baconpaul ,
Thanks for the PR!
I don't think we need to keep `tailGet(const clap_plugin_t *plugin) const` around, maybe we just break the helper API?
I suspect the tail wasn't used at all.
Cheers :+1:

**Comment by baconpaul** [comment]
> Hi @baconpaul ,
> Thanks for the PR!
> I don't think we need to keep `tailGet(const clap_plugin_t *plugin) const` around, maybe we just break the helper API?
> I suspect the tail wasn't used at all.
> Cheers 👍

The clap juce wrappers all use tail! 

But I can adapt them in synch sure. Lemme push now

**Comment by baconpaul** [comment]
Anyway check out that version. If that's good I can update the juce wrapper and then update surge and CSD.

**Comment by abique** [comment]
Thank you very much! :-)

**Pull request merged**
