### PR TITLE
Add CLAP_HELPERS_UNLIKELY

### LINKED ISSUE #29: [[unlikely]] attribute requires C++20
Moved over from https://github.com/free-audio/clap/pull/364

The problem is that the `[[unlikely]]` attribute is used in `host.hxx` but it is not compatible with C++17 as it requires C++20 or higher.

My suggestion would be to define a `CLAP_HELPERS_UNLIKELY` somewhere. But where exactly? In a new header called macros? Or just in `host.hxx` for now?

### PR DESCRIPTION
**Pull request by Trinitou**
resolves #29

### CODE REVIEW

**Comment by abique** [comment]
Maybe introduce a `macros.hh` to put it there?

**Comment by Trinitou** [comment]
Putting the define into `host.hxx` is the most easy solution. Or do you think it's better to put the define into a separate header (e.g. a new `private/macros.h` file) to potentially be used by other `clap-helpers` as well in the future?

**Comment by Trinitou** [comment]
better in a `private` subfolder or OK like this?

**Comment by abique** [comment]
Looks good like this.

**Pull request merged**
