### PR TITLE
PresetDiscoveryProvider: fix error message

### PR DESCRIPTION
**Pull request by Trinitou**

### CODE REVIEW

**Comment by baconpaul** [comment]
Can you please re-point this against next? Thank you!

**Comment by Trinitou** [comment]
doesn't contain #54 so actually shouldn't be a problem (?)

**Comment by baconpaul** [comment]
Well lets chat on discord but my thinking is: if we have some commits in main not in next, when we move next to main we run the risk of losing them.

**Comment by Trinitou** [comment]
> Can you please re-point this against next? Thank you!

done

**Comment by baconpaul** [comment]
And merged!

**Pull request merged**
